import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { NextUiProvider } from '../components/providers/NextUiProvider'
import { Navbar } from '../components/Navbar'
import TanstackProvider from '../components/providers/TanstackProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'EComm cafe',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TanstackProvider>
          <NextUiProvider>
            <Navbar />
            {children}
          </NextUiProvider>
        </TanstackProvider>
      </body>
    </html>
  )
}
